version: "3.9"
services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src:ro
      - ./artifacts:/app/artifacts:ro
      - ./mlruns:/app/mlruns:ro
    environment:
      - PYTHONUNBUFFERED=1
      - MLFLOW_TRACKING_URI=file:/app/mlruns
